### ISSUE TITLE
Для работы потребуется SSH Server

### ISSUE THREAD

**Issue by edgiru** [maxlinus/TightVNCHELPDESK#2]
Извините немного не понятно. Требуется просто SSH сервер на Ubuntu и все? На него не надо устанавливать RepiterVNC под linux? И еще вопрос сервер к примеру поднят на виртуалке Oracle благо они у них бесплатны. Там у SSH нельзя заходить по имени и паролю там только исключительно сертификаты(ключи). Подскажите как быть в этом случае?

**Comment by maxlinus** [comment]
да только SSH сервер, и открытые нужные порты, хорошо расписана инструкция тут https://null.la/ , вкладка сервер.
Для подключения к ssh используется [kitty](http://www.9bis.net/kitty/#!index.md) , вы можете в [ней настроить ](https://flops.ru/kb/knowledge-base/kak-ispolyzovaty-ssh-klyutchi-s-putty/)доступ по ключам и пользоваться вместо паролей.
